CREATE DATABASE IF NOT EXISTS mednet; 

CREATE TABLE IF NOT EXISTS mednet.images (
  `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `fileName` VARCHAR(255) NOT NULL,
  `date` TIMESTAMP NULL,
  `label` VARCHAR(31) NULL
)